services:
  Dbp\Relay\GreenlightConnectorCampusonlineBundle\Service\LdapService:
    autowire: true
    autoconfigure: true
    calls:
      - setLDAPCache: [ '@dbp.relay.greenlight_connector_campusonline.cache.ldap', 360 ]

  Dbp\Relay\GreenlightConnectorCampusonlineBundle\Service\CampusonlineService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\GreenlightConnectorCampusonlineBundle\Service\PersonPhotoProvider:
    autowire: true
    autoconfigure: true

  Dbp\Relay\GreenlightConnectorCampusonlineBundle\Command\PictureFetchCommand:
    public: false
    autowire: true
    autoconfigure: true

  Dbp\Relay\GreenlightConnectorCampusonlineBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\GreenlightConnectorCampusonlineBundle\EventSubscriber\ProxyDataEventSubscriber:
    autowire: true
    autoconfigure: true

  Dbp\Relay\GreenlightBundle\API\PersonPhotoProviderInterface:
    '@Dbp\Relay\GreenlightConnectorCampusonlineBundle\Service\PersonPhotoProvider'

  dbp.relay.greenlight_connector_campusonline.cache.ldap:
    parent: cache.app
    tags:
      - { name: 'cache.pool', default_lifetime: 360 }